spring:
  profiles:
    active: dev
  application:
    name: 'Application name'

---
# production properties
spring:
  config:
    activate:
      on-profile: prod

---
# dev properties
spring:
  config:
    activate:
      on-profile: dev

---
# test properties
spring:
  config:
    activate:
      on-profile: test
